### PR TITLE
Finer Label selectors

### PR DESCRIPTION
**Pull request by acseven**
Hi,
I hope you don't mind, I've made this small edit to be able to  customise the labels a bit better. Working example [here](https://adrianon.com/#adriano-neves-photo-1/0/UK_20160420-172823-Straight-Ahead-United-Kingdom-London_acn_1600L_100JPG.jpg) (click for caption).

Att: I'm in no way an experienced programmer, but I [think I] can get by with simpler stuff. If I have time I may delve a bit further into reviewing the functionality of the plugin, namely adding lenses to the EXIF info.

Cheers

### CODE REVIEW

**Comment by kristarella** [comment]
@acseven thanks so much for contributing!

I think I didn’t include this in my original plugin because you can actually use the other fields for this.

Like this: https://cloudup.com/c7T3N41azoo

Although using %s in the same field twice breaks something, so I might need to look into that.

Let me know what you think.

**Comment by acseven** [comment]
Hi @kristarella - thanks for having a look. I made this edit a while ago and I think at the time the issue I found was that the way it was implemented made it difficult to style the label and the field independently - this way it was easier to address different stylings to both.There could be another do it though, maybe by  using CSS only, but at the time that's what I came up with to address the issue. 
This is how I am using it:
scrn

**Comment by kristarella** [comment]
@acseven I am still reluctant to include this change because I think it adds unnecessary fields to the options. I'm pretty sure you can do the exact same thing adding your HTML in the existing fields like this:

screen shot 2018-10-12 at 11 54 44 am

**Comment by acseven** [comment]
Thanks for the reply. I see your point and it should work, but in truth I can't get what you have there working. Label tags get striped out and depending on the edit, even `<li>`. In retrospect, I think this was why I changed the code. 

This:
s

Results in this:

`<ul id="wp-image-3726" class="exif">Aperture:ƒ/3.5Focal length:7.9mmISO:80Shutter speed:1/400s</ul>`

**Pull request closed without merging**
